export const AlbumActionTypes = {
  FETCH_ALBUMS_STARTED: 'FETCH_ALBUMS_STARTED',
  FETCH_ALBUMS_COMPLETED: 'FETCH_ALBUMS_COMPLETED',
  FETCH_ALBUMS_ERROR: 'FETCH_ALBUMS_ERROR',
  MARK_AS_FAVOURITE_ALBUM: 'MARK_AS_FAVOURITE_ALBUM',
  MARK_AS_FAVOURITE_ALBUM_ERROR: 'MARK_AS_FAVOURITE_ALBUM_ERROR',
  UNMARK_FROM_FAVOURITE_ALBUM: 'UNMARK_FROM_FAVOURITE_ALBUM',
  UNMARK_FROM_FAVOURITE_ALBUM_ERROR: 'UNMARK_FROM_FAVOURITE_ALBUM_ERROR',
};

export const TracksActionTypes = {
  FETCH_TRACKS_STARTED: 'FETCH_TRACKS_STARTED',
  FETCH_TRACKS_COMPLETED: 'FETCH_TRACKS_COMPLETED',
  FETCH_TRACKS_ERROR: 'FETCH_TRACKS_ERROR',
};
